# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

import sphinx_rtd_theme
import sphinx_fontawesome


# -- Project information -----------------------------------------------------

project = 'Handbuch Opendata.swiss'
copyright = '2020, bfs.admin.ch'
author = 'bfs.admin.ch'

# The full version, including alpha/beta/rc tags
release = '1.0'

pygments_style = 'monokai'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx_rtd_theme',
    'sphinx_fontawesome',
    'sphinx.ext.extlinks',
]

extlinks = {
    'bfs-library':
        ('https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/ogd/dokumentation.html/%s', ''),
    'bfs-m9-textbausteine-fuer-standardformulierungen':
        ('https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/ogd/dokumentation.assetdetail.11147090.html/%s', ''),
    'bfs-m7-arbeitshilfe-behoerden-publikation-ogd':
        ('https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/ogd/dokumentation.assetdetail.11147071.html/%s', ''),
    'bfs-m5-abgrenzung-kundenspezifische-leistungen-ogd':
        ('https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/ogd/dokumentation.assetdetail.11147081.html/%s', ''),
    'bfs-m4-bericht-datenbestaende-bund':
        ('https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/ogd/dokumentation.assetdetail.11147084.html/%s', ''),
    'bfs-m1-rechtliche-rahmenbedingungen':
        ('https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/ogd/dokumentation.assetdetail.11147095.html/%s', ''),
    'bfs-opengovernmentdata-grundlagenstudie-schweiz':
        ('https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/ogd/dokumentation.assetdetail.11147076.html/%s', ''),
    'bfs-ogd-strategischer-schwerpunkt-im-egovernment':
        ('https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/ogd/dokumentation.assetdetail.11147073.html/%s', ''),
    'bfs-wirtschaftliche-auswirkungen-ogd':
        ('https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/ogd/dokumentation.assetdetail.11147089.html/%s', ''),
    'bfs-massnahmen-aufbau-ogd-kultur':
        ('https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/ogd/dokumentation.assetdetail.11147079.html/%s', ''),
    'bfs-bericht-ogd-international':
        ('https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/ogd/dokumentation.assetdetail.11147056.html/%s', ''),
    'bfs-strategieumsetzung-ogd-schweiz-pruefung':
        ('https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/ogd/dokumentation.assetdetail.11147034.html/%s', ''),
    'email-to-bfs':
        ('mailto:opendata@bfs.admin.ch/%s', ''),
    'federal-gazette-ogd-strategie-2014-2018':
        ('https://www.admin.ch/opc/de/federal-gazette/2014/3493.pdf/%s', ''),
    'federal-gazette-ogd-strategie-2019-2023':
        ('https://www.admin.ch/opc/de/federal-gazette/2019/879.pdf/%s', ''),
    'ech-0200-dcat':
        ('https://www.ech.ch/de/standards/39919/%s', ''),
    'opendata-swiss-portal':
        ('https://opendata.swiss/%s', ''),
    'opendata-swiss-terms-of-use':
        ('https://opendata.swiss/de/terms-of-use/%s', ''),
    'geocat-startseite':
        ('https://www.geocat.admin.ch/de/startseite.html/%s', ''),
    'geocat-gm03':
        ('https://www.geocat.admin.ch/de/dokumentation/gm03.html/%s', ''),
    'geocat-xml-example':
        ('https://www.geocat.ch/geonetwork/srv/ger/xml.metadata.get?uuid=c5bc9d6b-cafb-4617-97d7-868ab4cd5506/%s', ''),
    'geocat-anleitung-publikation-auf-opendata-swiss':
        ('https://www.geocat.admin.ch/de/dokumentation/opendata.html/%s', ''),
    'geocat-portal':
        ('http://www.geocat.ch/%s', ''),
    'geoadmin-bgdi':
        ('https://www.geo.admin.ch/de/about-swiss-geoportal/task-and-responsabilities/bundes-geodaten-infrastruktur.html/%s', ''),
    'wikipedia-iso8601':
        ('https://en.wikipedia.org/wiki/ISO_8601/%s', ''),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'de'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# These paths are either relative to html_static_path
# or fully qualified paths (eg. https://...)
html_css_files = [
    'css/custom.css',
]

html_js_files = [
    'js/custom.js',
]

html_theme_options = {
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': False,
    'navigation_depth': 1,
    'includehidden': False,
    'titles_only': True,
    'logo_only': True,
    'prev_next_buttons_location': None,
    'style_external_links': True,
}

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = '_static/images/branding/favicon.ico'


html_logo = '_static/images/branding/handbook_logo.svg'
