# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

import sphinx_rtd_theme
import sphinx_fontawesome


# -- Project information -----------------------------------------------------

project = 'Handbuch Opendata.swiss'
copyright = '2020, bfs.admin.ch'
author = 'bfs.admin.ch'

# The full version, including alpha/beta/rc tags
release = '1.0'

pygments_style = 'friendly'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx_rtd_theme',
    'sphinx_fontawesome',
    'notfound.extension',
    'sphinxcontrib.contentui'
]

notfound_no_urls_prefix = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'de'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# These paths are either relative to html_static_path
# or fully qualified paths (eg. https://...)
html_css_files = [
    'css/custom.css',
]

html_js_files = [
    'js/custom.js',
]

html_theme_options = {
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': False,
    'navigation_depth': 1,
    'includehidden': False,
    'titles_only': True,
    'logo_only': True,
    'prev_next_buttons_location': None,
    'style_external_links': True,
}

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = '_static/images/branding/favicon.ico'


html_logo = '_static/images/branding/handbook_logo.png'

# check links
nitpicky = True

# -- Options for sphinx-intl -------------------------------------------------

locale_dirs = ['locale/']
gettext_compact = False
