name: Build and Deploy
on: [push, workflow_dispatch] # Trigger this action manually - and temporarily on push
env:
  PIP_CACHE_DIR: ".cache/pip"
jobs:
  build_and_deploy_to_test:
    container: python:latest
    runs-on: ubuntu-latest
    environment: test
    env:
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DEST_PATH: ${{ secrets.DEST_PATH }}
      HOSTNAME: ${{ secrets.HOSTNAME }}
      ENABLE_HYPOTHESIS: "true"
      ROBOTS_DIRECTIVE: "noindex"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Setup
        run: ./.github/scripts/setup.sh
      - name: Deploy
        run: ./.github/scripts/deploy.sh

  build_and_deploy_to_prod:
    if: contains( github.ref, 'master') # Only run this action for the master branch
    container: python:latest
    runs-on: ubuntu-latest
    environment: prod
    env:
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DEST_PATH: ${{ secrets.DEST_PATH }}
      HOSTNAME: ${{ secrets.HOSTNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Setup
        run: ./.github/scripts/setup.sh
      - name: Deploy
        run: ./.github/scripts/deploy.sh
