name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v1
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.liip.ch/ogdch/ogdch-handbook-ci"
        env:
          FOLLOW_TAGS: "false"
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "gitlab.liip.ch"
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "3846"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
